# Site
name: "Yanachka"
title: "ינהצ׳קה"
description: "😻🎁  בובות בעבודת יד"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-177604941-1'
disqus: 'demowebsite'
mailchimp-list: 
include: ["_pages"]
permalink: /:title/
email: mzsrtgzr2@gmail.com
formspree: xknavlkz

# Authors
authors:
  yana:
    name: ינהצ׳קה
    display_name: ינהצ׳קה
    avatar: 'assets/images/avatar.png'
    web: https://www.facebook.com/yanachka.store
    description: "הזמנה אישית ומיוחדת של עבודות יד בסריגה ויצירה. באהבה גדולה מכל הלב"
  
# Plugins
plugins:
  # - jekyll-paginate
  # - jekyll-sitemap
  # - jekyll-feed
  # - jekyll-seo-tag
  # - jekyll-archives
  # - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 1000
paginate_path: /page:num/
    
# Other
# highlighter: none
# markdown: kramdown
# kramdown:
#    syntax_highlighter_opts:
#       disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
